### ISSUE TITLE
No module name described in MANIFEST

### ISSUE THREAD

**Issue by gselzer** [leangen/geantyref#10]
For those using JPMS, it would be nice if geantyref contained an Automatic Module Name (see [here](https://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html) for reasons why). This would provide a stable module name that other projects can reference, and is a very small change on the part of geantyref (see [here](http://branchandbound.net/blog/java/2017/12/automatic-module-name/)).

**Comment by kaqqao** [comment]
I was looking into this myself. I'm currently unable to actively work on my projects, but if you'd take this upon yourself I'd happily merge and release it.
If not, I'll eventually resume active work and take care of this, but can't give promises about the time line.

**Comment by gselzer** [comment]
@kaqqao I would be happy to add it. Do you have any preferences about the module name? I would assume `io.leangen.geantyref`?

**Comment by kaqqao** [comment]
Yup, looks good! Merged, thanks!

**Comment by A248** [comment]
@kaqqao I don't mean to bug you about a release, but you did say you'd release a minor version with Automatic-Module-Name. This issue is a pretty significant blocker for any modular application, so it'd be nice if that release could arrive in the nearer future, if you have the spare time of course.
