### ISSUE TITLE
getExactParameterTypes() for constructors

### ISSUE THREAD

**Issue by pniederw** [leangen/geantyref#2]
I would be useful to support `getExactParameterTypes()` not only for methods but also for constructors.

Given that geantyref already requires Java 1.8+, the easiest way to accomplish this is to change the method signature

`public static AnnotatedType[] getExactParameterTypes(Method m, AnnotatedType declaringType)`

to

`public static AnnotatedType[] getExactParameterTypes(Executable m, AnnotatedType declaringType)`

Likewise for the `Type` overload. No other changes required.

PS: Since `Type` overloads are implemented in terms of `AnnotatedType` overloads but discard annotation information, would it be more efficient to lift `Type` to `AnnotatedType` using `new AnnotatedTypeImpl(type)` rather than `annotate(type)`?

**Comment by kaqqao** [comment]
Thanks for this! I fixed it in v1.1.1.

And you're absolutely right about `new AnnotatedTypeImpl(type)` vs `annotate(type)`. I'll replace it.
