### ISSUE TITLE
ParameterizedTypeImpl `toString()` method returns wrong method name for nested classes

### ISSUE THREAD

**Issue by hgschmie** [leangen/geantyref#24]
Consider this: 

<img width="883" alt="Screenshot 2024-01-19 at 12 17 55" src="https://github.com/leangen/geantyref/assets/39495/852c6c0c-ab4c-44f6-9389-22025c5cc31e">

While the ParameterizedTypeImpl (which is part of geantryref) returns `io.leangen.geantyref.Issue20Test.UnitX<io.leangen.geantyref.Issue20Test$QuantityX>`, the actual class name is `io.leangen.geantyref.Issue20Test$UnitX` as `UnitX` is a nested class within the `Issue20Test` class. But the toString() method omits the `$` as a marker for a nested class and uses a `.`

**Comment by kaqqao** [comment]
Similar to #23, this is a result of changes in Java itself... While there is no spec for these strings and JDK is free to change them, it is mind boggling to me that they actually do.
